### ISSUE TITLE
Include original source

### ISSUE THREAD

**Issue by paulbovbel** [optimans/cockpit-zfs-manager#5]
Great project! Would you consider including the original source, instead of packed artifacts? It would:
- enable people to contribute PRs to your project
- allow people to audit the code before running against their pools

I'd be happy to contribute a CI job to build the project, and maybe even ship deb packages.

https://github.com/cockpit-project/cockpit/issues/3519#issuecomment-567087354

**Comment by iamoptimans** [comment]
Hi Paul,

Thanks for the feedback. Can't believe how much interest has been generated, considering it was started originally to make administration easier for myself. Great to see it is able to help others.

The project at the moment is the original source. HTML code is currently static. I don't know React yet, however it is part of my roadmap to learn and convert the code.

For code auditing, I can make commits for changes instead of release changes in the future, which should help reviewing.

CI job sounds great, am new to GitHub, so will need help with this. Would it be possible for RPM packages as well?

**Comment by paulbovbel** [comment]
Mea culpa, when I saw...
![image](https://user-images.githubusercontent.com/1694370/75903521-b3a9ee00-5e0f-11ea-9aa8-32fa14588c52.png)

... I made the assumption that this was some packaged up artifact. After looking inside, I do see that it is indeed, the original source.
